from .env import (
    VampireKillerEnv,
    EnvConfig,
    ACTION_SET_VERSION,
    ACTION_NOOP,
    ACTION_RIGHT,
    ACTION_LEFT,
    ACTION_UP,
    ACTION_DOWN,
    ACTION_ATTACK,
    ACTION_RIGHT_JUMP,
    ACTION_LEFT_JUMP,
    ACTION_RIGHT_JUMP_ATTACK,
    ACTION_LEFT_JUMP_ATTACK,
)

